const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today",
    signOut: "Sign Out",
    play: "Play",
    moreInfo: "More Info",
    nowPlaying: "Now Playing",
    Popular: "Popular",
    topRated: "Top Rated",
    upcoming: "UpComing",
  },
  telugu: {
    search: "వెతకండి",
    gptSearchPlaceholder: "మీరు ఈరోజు ఏమి చూడాలనుకుంటున్నారు?",
    signOut: "సైన్ అవుట్",
    play: "ప్రారంభించు",
    moreInfo: "మరింత సమాచారం",
    nowPlaying: "ఇప్పుడు చూపుతోంది",
    Popular: "జనాదరణ పొందినది",
    topRated: "అగ్రశ్రేణి",
    upcoming: "రాబోయే",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे",
    signOut: "साइन आउट",
    play: "खेल",
    moreInfo: "और जानकारी",
    nowPlaying: "अब खेल रहे हैं",
    Popular: "लोकप्रिय",
    topRated: "टॉप रेटेड",
    upcoming: "आगामी",
  },
  spanish: {
    search: "buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    signOut: "desconectar",
    play: "jugar",
    moreInfo: "más información",
    nowPlaying: "Jugando ahora",
    Popular: "Popular",
    topRated: "los más valorados",
    upcoming: "próximo",
  },
};

export default lang;
